/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package calcw7;

import java.awt.event.KeyEvent;


/**
 *
 * @author Aluno Tarde
 */
public class Calc extends javax.swing.JFrame {
    
   

    
    /**
     * Creates new form Calc
     */
    public Calc() {
        initComponents();
        setLocationRelativeTo(null);
        Tela.setBorder(null);
        Telab.setBorder(null);
        Eme.setBorder(null);
        Eme.setBorder(null);
        Tela.setText("0");
    }
    char operador;
    double Raiz=0,Umxiz=0,Maismenos,Neg1,Memoria=0,num1=' ',num2,porcent,d=0;
    String digtest2;
    double digtest,digtest3,teste;
    boolean ponto,apagador,refaz;

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        b3 = new javax.swing.JButton();
        jMenu3 = new javax.swing.JMenu();
        jMenuItem4 = new javax.swing.JMenuItem();
        jRadioButtonMenuItem2 = new javax.swing.JRadioButtonMenuItem();
        jMenuItem6 = new javax.swing.JMenuItem();
        jMenuBar2 = new javax.swing.JMenuBar();
        jMenu4 = new javax.swing.JMenu();
        jMenu5 = new javax.swing.JMenu();
        jMenuItem20 = new javax.swing.JMenuItem();
        b1 = new javax.swing.JButton();
        b2 = new javax.swing.JButton();
        b4 = new javax.swing.JButton();
        b5 = new javax.swing.JButton();
        Clearev = new javax.swing.JButton();
        b8 = new javax.swing.JButton();
        b9 = new javax.swing.JButton();
        b10 = new javax.swing.JButton();
        b12 = new javax.swing.JButton();
        b13 = new javax.swing.JButton();
        b17 = new javax.swing.JButton();
        b19 = new javax.swing.JButton();
        b21 = new javax.swing.JButton();
        b22 = new javax.swing.JButton();
        Ponto = new javax.swing.JButton();
        b25 = new javax.swing.JButton();
        b26 = new javax.swing.JButton();
        b27 = new javax.swing.JButton();
        b28 = new javax.swing.JButton();
        b29 = new javax.swing.JButton();
        b11 = new javax.swing.JButton();
        b14 = new javax.swing.JButton();
        b15 = new javax.swing.JButton();
        b16 = new javax.swing.JButton();
        b18 = new javax.swing.JButton();
        b20 = new javax.swing.JButton();
        b24 = new javax.swing.JButton();
        b30 = new javax.swing.JButton();
        Tela = new javax.swing.JTextField();
        Telab = new javax.swing.JTextField();
        Eme = new javax.swing.JTextField();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jRadioButtonMenuItem1 = new javax.swing.JRadioButtonMenuItem();
        jMenuItem1 = new javax.swing.JMenuItem();
        jMenuItem2 = new javax.swing.JMenuItem();
        jMenuItem3 = new javax.swing.JMenuItem();
        jSeparator2 = new javax.swing.JPopupMenu.Separator();
        jMenuItem10 = new javax.swing.JMenuItem();
        jMenuItem5 = new javax.swing.JMenuItem();
        jSeparator1 = new javax.swing.JPopupMenu.Separator();
        jRadioButtonMenuItem4 = new javax.swing.JRadioButtonMenuItem();
        jMenuItem7 = new javax.swing.JMenuItem();
        jMenuItem8 = new javax.swing.JMenuItem();
        jMenu6 = new javax.swing.JMenu();
        jMenuItem11 = new javax.swing.JMenuItem();
        jMenuItem12 = new javax.swing.JMenuItem();
        jMenuItem13 = new javax.swing.JMenuItem();
        jMenuItem14 = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        jMenuItem9 = new javax.swing.JMenuItem();
        jMenuItem15 = new javax.swing.JMenuItem();
        jSeparator3 = new javax.swing.JPopupMenu.Separator();
        jMenu8 = new javax.swing.JMenu();
        jMenuItem17 = new javax.swing.JMenuItem();
        jMenuItem18 = new javax.swing.JMenuItem();
        jMenuItem19 = new javax.swing.JMenuItem();
        jMenuItem21 = new javax.swing.JMenuItem();
        jMenu7 = new javax.swing.JMenu();
        jMenuItem16 = new javax.swing.JMenuItem();
        jMenuItem22 = new javax.swing.JMenuItem();

        b3.setText("1");

        jMenu3.setText("jMenu3");

        jMenuItem4.setText("jMenuItem4");

        jRadioButtonMenuItem2.setSelected(true);
        jRadioButtonMenuItem2.setText("jRadioButtonMenuItem2");

        jMenuItem6.setText("jMenuItem6");

        jMenu4.setText("File");
        jMenuBar2.add(jMenu4);

        jMenu5.setText("Edit");
        jMenuBar2.add(jMenu5);

        jMenuItem20.setText("jMenuItem20");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("CJ - Calculadora Java");
        setResizable(false);

        b1.setText("0");
        b1.setActionCommand("1");
        b1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b1ActionPerformed(evt);
            }
        });
        b1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                b1KeyReleased(evt);
            }
        });

        b2.setText("←");
        b2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b2ActionPerformed(evt);
            }
        });

        b4.setText("1");
        b4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b4ActionPerformed(evt);
            }
        });
        b4.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                b4KeyReleased(evt);
            }
        });

        b5.setText("4");
        b5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b5ActionPerformed(evt);
            }
        });
        b5.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                b5KeyReleased(evt);
            }
        });

        Clearev.setText("CE");
        Clearev.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ClearevActionPerformed(evt);
            }
        });

        b8.setText("C");
        b8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b8ActionPerformed(evt);
            }
        });
        b8.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                b8KeyReleased(evt);
            }
        });

        b9.setText("MC");
        b9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b9ActionPerformed(evt);
            }
        });

        b10.setText("/");
        b10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b10ActionPerformed(evt);
            }
        });

        b12.setText("9");
        b12.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b12ActionPerformed(evt);
            }
        });
        b12.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                b12KeyReleased(evt);
            }
        });

        b13.setText("+");
        b13.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b13ActionPerformed(evt);
            }
        });

        b17.setText("-");
        b17.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b17ActionPerformed(evt);
            }
        });

        b19.setText("3");
        b19.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b19ActionPerformed(evt);
            }
        });
        b19.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                b19KeyReleased(evt);
            }
        });

        b21.setText("±");
        b21.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b21ActionPerformed(evt);
            }
        });

        b22.setText("*");
        b22.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b22ActionPerformed(evt);
            }
        });

        Ponto.setText(",");
        Ponto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PontoActionPerformed(evt);
            }
        });

        b25.setText("6");
        b25.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b25ActionPerformed(evt);
            }
        });
        b25.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                b25KeyReleased(evt);
            }
        });

        b26.setMnemonic('2');
        b26.setText("2");
        b26.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b26ActionPerformed(evt);
            }
        });
        b26.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                b26KeyReleased(evt);
            }
        });

        b27.setText("5");
        b27.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b27ActionPerformed(evt);
            }
        });
        b27.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                b27KeyReleased(evt);
            }
        });

        b28.setText("7");
        b28.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b28ActionPerformed(evt);
            }
        });
        b28.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                b28KeyReleased(evt);
            }
        });

        b29.setText("8");
        b29.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b29ActionPerformed(evt);
            }
        });
        b29.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                b29KeyReleased(evt);
            }
        });

        b11.setText("MR");
        b11.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b11ActionPerformed(evt);
            }
        });

        b14.setText("MS");
        b14.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b14ActionPerformed(evt);
            }
        });

        b15.setText("M+");
        b15.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b15ActionPerformed(evt);
            }
        });

        b16.setText("M-");
        b16.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b16ActionPerformed(evt);
            }
        });

        b18.setText("√");
        b18.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b18ActionPerformed(evt);
            }
        });

        b20.setText("%");
        b20.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b20ActionPerformed(evt);
            }
        });

        b24.setText("1/x");
        b24.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b24ActionPerformed(evt);
            }
        });

        b30.setText("=");
        b30.setMaximumSize(new java.awt.Dimension(49, 23));
        b30.setMinimumSize(new java.awt.Dimension(49, 23));
        b30.setPreferredSize(new java.awt.Dimension(50, 23));
        b30.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b30ActionPerformed(evt);
            }
        });

        Tela.setFont(new java.awt.Font("Consolas", 0, 18)); // NOI18N
        Tela.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        Tela.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TelaActionPerformed(evt);
            }
        });

        Telab.setEditable(false);
        Telab.setBackground(new java.awt.Color(255, 255, 255));
        Telab.setFont(new java.awt.Font("Arial", 0, 11)); // NOI18N
        Telab.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        Telab.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TelabActionPerformed(evt);
            }
        });

        Eme.setEditable(false);
        Eme.setBackground(new java.awt.Color(255, 255, 255));
        Eme.setFont(new java.awt.Font("Calibri", 0, 12)); // NOI18N
        Eme.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        Eme.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EmeActionPerformed(evt);
            }
        });

        jMenu1.setText("Exibir");

        jRadioButtonMenuItem1.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_1, java.awt.event.InputEvent.ALT_MASK));
        jRadioButtonMenuItem1.setSelected(true);
        jRadioButtonMenuItem1.setText("Padrão");
        jRadioButtonMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButtonMenuItem1ActionPerformed(evt);
            }
        });
        jMenu1.add(jRadioButtonMenuItem1);

        jMenuItem1.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_2, java.awt.event.InputEvent.ALT_MASK));
        jMenuItem1.setText("Científica");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem1);

        jMenuItem2.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_3, java.awt.event.InputEvent.ALT_MASK));
        jMenuItem2.setText("Programador");
        jMenu1.add(jMenuItem2);

        jMenuItem3.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_4, java.awt.event.InputEvent.ALT_MASK));
        jMenuItem3.setText("Estatística");
        jMenu1.add(jMenuItem3);
        jMenu1.add(jSeparator2);

        jMenuItem10.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_H, java.awt.event.InputEvent.CTRL_MASK));
        jMenuItem10.setText("Histórico");
        jMenu1.add(jMenuItem10);

        jMenuItem5.setText("Agrupamento de dígitos");
        jMenu1.add(jMenuItem5);
        jMenu1.add(jSeparator1);

        jRadioButtonMenuItem4.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_F4, java.awt.event.InputEvent.CTRL_MASK));
        jRadioButtonMenuItem4.setSelected(true);
        jRadioButtonMenuItem4.setText("Básico");
        jMenu1.add(jRadioButtonMenuItem4);

        jMenuItem7.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_U, java.awt.event.InputEvent.CTRL_MASK));
        jMenuItem7.setText("Conversão de unidades");
        jMenu1.add(jMenuItem7);

        jMenuItem8.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_E, java.awt.event.InputEvent.CTRL_MASK));
        jMenuItem8.setText("Cálculo de data");
        jMenu1.add(jMenuItem8);

        jMenu6.setText("Planinhas");

        jMenuItem11.setText("Hipoteca");
        jMenu6.add(jMenuItem11);

        jMenuItem12.setText("Leasing de veículo");
        jMenuItem12.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem12ActionPerformed(evt);
            }
        });
        jMenu6.add(jMenuItem12);

        jMenuItem13.setText("Economia de combustível(Km/l)");
        jMenu6.add(jMenuItem13);

        jMenuItem14.setText("Economia de combustível(1/100 km)");
        jMenuItem14.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem14ActionPerformed(evt);
            }
        });
        jMenu6.add(jMenuItem14);

        jMenu1.add(jMenu6);

        jMenuBar1.add(jMenu1);

        jMenu2.setText("Editar");

        jMenuItem9.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_C, java.awt.event.InputEvent.CTRL_MASK));
        jMenuItem9.setText("Copiar");
        jMenu2.add(jMenuItem9);

        jMenuItem15.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_V, java.awt.event.InputEvent.CTRL_MASK));
        jMenuItem15.setText("Colar");
        jMenu2.add(jMenuItem15);
        jMenu2.add(jSeparator3);

        jMenu8.setText("Histórico");

        jMenuItem17.setText("Copiar histórico");
        jMenuItem17.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem17ActionPerformed(evt);
            }
        });
        jMenu8.add(jMenuItem17);

        jMenuItem18.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_F2, 0));
        jMenuItem18.setText("Editar");
        jMenu8.add(jMenuItem18);

        jMenuItem19.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_ESCAPE, 0));
        jMenuItem19.setText("Cancelar edição");
        jMenuItem19.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem19ActionPerformed(evt);
            }
        });
        jMenu8.add(jMenuItem19);

        jMenuItem21.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_D, java.awt.event.InputEvent.SHIFT_MASK | java.awt.event.InputEvent.CTRL_MASK));
        jMenuItem21.setText("Limpar");
        jMenu8.add(jMenuItem21);

        jMenu2.add(jMenu8);

        jMenuBar1.add(jMenu2);

        jMenu7.setText("Ajuda");

        jMenuItem16.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_F1, 0));
        jMenuItem16.setText("Exibir Ajuda");
        jMenuItem16.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem16ActionPerformed(evt);
            }
        });
        jMenu7.add(jMenuItem16);

        jMenuItem22.setText("Sobre");
        jMenuItem22.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem22ActionPerformed(evt);
            }
        });
        jMenu7.add(jMenuItem22);

        jMenuBar1.add(jMenu7);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(Telab)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(b2, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(6, 6, 6)
                        .addComponent(Clearev, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(6, 6, 6)
                        .addComponent(b8, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(6, 6, 6)
                        .addComponent(b21, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(6, 6, 6)
                        .addComponent(b18, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(b28, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(6, 6, 6)
                        .addComponent(b29, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(6, 6, 6)
                        .addComponent(b12, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(6, 6, 6)
                        .addComponent(b10, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(6, 6, 6)
                        .addComponent(b20, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(b4, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(6, 6, 6)
                                .addComponent(b26, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(b1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(6, 6, 6)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(Ponto, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(b19, javax.swing.GroupLayout.DEFAULT_SIZE, 49, Short.MAX_VALUE))
                        .addGap(6, 6, 6)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(b17, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(b13, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(6, 6, 6)
                        .addComponent(b30, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(b9)
                        .addGap(6, 6, 6)
                        .addComponent(b11)
                        .addGap(6, 6, 6)
                        .addComponent(b14)
                        .addGap(6, 6, 6)
                        .addComponent(b15)
                        .addGap(6, 6, 6)
                        .addComponent(b16, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(b5, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(6, 6, 6)
                        .addComponent(b27, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(6, 6, 6)
                        .addComponent(b25, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(6, 6, 6)
                        .addComponent(b22, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(6, 6, 6)
                        .addComponent(b24, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(1, 1, 1))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(Eme, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, 0)
                        .addComponent(Tela)))
                .addContainerGap())
        );

        layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {Clearev, Ponto, b10, b11, b12, b13, b14, b15, b16, b17, b18, b19, b2, b20, b21, b22, b25, b26, b27, b28, b29, b4, b5, b8, b9});

        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(Telab, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(Tela, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Eme, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(6, 6, 6)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(b9)
                    .addComponent(b11)
                    .addComponent(b14)
                    .addComponent(b15)
                    .addComponent(b16))
                .addGap(6, 6, 6)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(b2)
                    .addComponent(Clearev)
                    .addComponent(b8)
                    .addComponent(b21)
                    .addComponent(b18))
                .addGap(6, 6, 6)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(b28)
                    .addComponent(b29)
                    .addComponent(b12)
                    .addComponent(b10)
                    .addComponent(b20))
                .addGap(6, 6, 6)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(b5)
                    .addComponent(b27)
                    .addComponent(b25)
                    .addComponent(b22)
                    .addComponent(b24))
                .addGap(6, 6, 6)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(b4)
                            .addComponent(b26))
                        .addGap(4, 4, 4)
                        .addComponent(b1))
                    .addComponent(b19)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(b17)
                        .addGap(4, 4, 4)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(b13)
                            .addComponent(Ponto)))
                    .addComponent(b30, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        layout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {Clearev, Ponto, b10, b11, b12, b13, b14, b15, b16, b17, b18, b19, b2, b20, b21, b22, b24, b25, b26, b27, b28, b29, b4, b5, b8, b9});

        pack();
    }// </editor-fold>//GEN-END:initComponents

    
    public void zerador (String num){
       if (Tela.getText().equals("0")){
           Tela.setText("");
           Tela.setText(Tela.getText() + num);
       }else{
        Tela.setText(Tela.getText() + num);   
       }
    }
    
    public void apaga (){
    if (apagador){
    Tela.setText("");
    apagador=false;}
    }
    
    public void remove () {
    teste=Double.parseDouble(Tela.getText());
    if((int)teste==teste){
        Tela.setText(String.valueOf((int)teste));
        teste=' ';}
    else{
        Tela.setText(String.valueOf(teste));
        teste=' ';}
    
    }
    
    public void removeB () {
    teste=Double.parseDouble(Tela.getText());
    if((int)teste==teste){
        Telab.setText(String.valueOf((int)teste));
        teste=' ';}
    else{
        Telab.setText(String.valueOf(teste));
        teste=' ';}
    
    }
    
    private void ClearevActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ClearevActionPerformed
        // TODO add your handling code here:
        ponto = false;
        Tela.setText("0");
        num1=num2=0;
        
    }//GEN-LAST:event_ClearevActionPerformed

    private void b11ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b11ActionPerformed
        // TODO add your handling code here:
        if(!ponto){
        Tela.setText(Tela.getText()+".");
        ponto = true;}
        if (Memoria ==0.0){
            Tela.setText("0");
        }else{
        Tela.setText(String.valueOf(Memoria));}
        remove();
        
    }//GEN-LAST:event_b11ActionPerformed

    private void PontoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PontoActionPerformed
        // TODO add your handling code here:
        if(!ponto){
        Tela.setText(Tela.getText()+".");
        ponto = true;}
    }//GEN-LAST:event_PontoActionPerformed

    private void b4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b4ActionPerformed
        // TODO add your handling code here:
        apaga();
         zerador ("1");
         refaz=false;
    }//GEN-LAST:event_b4ActionPerformed

    private void b26ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b26ActionPerformed
        // TODO add your handling code here:
        apaga();
        zerador ("2");
        refaz=false;
    }//GEN-LAST:event_b26ActionPerformed

    private void b19ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b19ActionPerformed
        // TODO add your handling code here:
        apaga();
        zerador ("3");
        refaz=false;
    }//GEN-LAST:event_b19ActionPerformed

    private void b5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b5ActionPerformed
        // TODO add your handling code here:
        apaga();
        zerador ("4");
        refaz=false;
    }//GEN-LAST:event_b5ActionPerformed

    private void b27ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b27ActionPerformed
        // TODO add your handling code here:
        apaga();
        zerador ("5");
        refaz=false;
    }//GEN-LAST:event_b27ActionPerformed

    private void b25ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b25ActionPerformed
        // TODO add your handling code here:
        apaga();
        zerador ("6");
        refaz=false;
    }//GEN-LAST:event_b25ActionPerformed

    private void b28ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b28ActionPerformed
        // TODO add your handling code here:
        apaga();
        zerador("7");
        refaz=false;
    }//GEN-LAST:event_b28ActionPerformed

    private void b29ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b29ActionPerformed
        // TODO add your handling code here:
        apaga();
        zerador("8");
        refaz=false;
    }//GEN-LAST:event_b29ActionPerformed

    private void b12ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b12ActionPerformed
        // TODO add your handling code here:
        apaga();
        zerador("9");
        refaz=false;
    }//GEN-LAST:event_b12ActionPerformed

    private void TelaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TelaActionPerformed

        apaga();
        Tela.setText("0");
    }//GEN-LAST:event_TelaActionPerformed

    private void b24ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b24ActionPerformed
        // TODO add your handling code here:
        teste=Double.parseDouble(Tela.getText());
        if(teste==0){
        Telab.setText("reciproc ("+Tela.getText()+")");
        Tela.setText("Impossivel dividir por zero");
        teste=' ';
        apagador=true;}
        else{
        Umxiz=1/Double.parseDouble(Tela.getText());
        Telab.setText("reciproc ("+Tela.getText()+")");
        Tela.setText(String.valueOf(Umxiz));
        remove();
        teste=' ';
        apagador=true;}
        
    }//GEN-LAST:event_b24ActionPerformed

    private void b1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b1ActionPerformed
        // TODO add your handling code here:
        apaga();
        zerador ("0");
    }//GEN-LAST:event_b1ActionPerformed

    private void b8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b8ActionPerformed
        // TODO add your handling code here:
        ponto = false;
        Tela.setText("0");
        num1=num2=' ';
        Telab.setText("");
        operador = ' ';
    }//GEN-LAST:event_b8ActionPerformed

    private void b13ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b13ActionPerformed
     
      
          ponto=false;
      apagador=true;
      if (num1==' '){
      num1=Double.parseDouble(Tela.getText());
      operador=('+');
      Telab.setText(Telab.getText() + " " + Tela.getText() + " +");
      refaz=true;}
      else { 
      if(!refaz){
        if(operador==('+')){
        num2=Double.parseDouble(Tela.getText());
        Telab.setText(Telab.getText() + " " + Tela.getText() + " +");
        num1=num1+num2;
        Tela.setText(String.valueOf(num1));
        remove();
        }
        else if (operador==('-')){
        num2=Double.parseDouble(Tela.getText());
        Telab.setText(Telab.getText() + " " + Tela.getText() + " +");
        num1=num1-num2;
        Tela.setText(String.valueOf(num1));
        remove();
        }
        else if (operador==('*')){
        num2=Double.parseDouble(Tela.getText());
        Telab.setText(Telab.getText() + " " + Tela.getText() + " +");
        num1=num1*num2;
        Tela.setText(String.valueOf(num1));
        remove();
        }
        else if (operador==('/')){
        num2=Double.parseDouble(Tela.getText());
        Telab.setText(Telab.getText() + " " + Tela.getText() + " +");
        num1=num1/num2;
        Tela.setText(String.valueOf(num1));
        remove();
        }
      operador=('+');
      refaz=true;
      }}
          
      
    }//GEN-LAST:event_b13ActionPerformed

    private void b9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b9ActionPerformed
        // TODO add your handling code here:
        Memoria=0;
        Eme.setText("");
    }//GEN-LAST:event_b9ActionPerformed

    private void b21ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b21ActionPerformed
        // TODO add your handling code here:
        Maismenos=Double.parseDouble(Tela.getText());
        Neg1=Double.parseDouble(Tela.getText());
        Maismenos=Maismenos*2;
        Neg1=Neg1-Maismenos;
        Tela.setText(String.valueOf(Neg1));
        remove();
        if (Neg1==0.0) {
        Tela.setText("0");}
        
    }//GEN-LAST:event_b21ActionPerformed

    private void b14ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b14ActionPerformed
        // TODO add your handling code here:
        Memoria=Double.parseDouble(Tela.getText());
        Eme.setText("M");
        if(Memoria==0){
            Eme.setText("");
        }
    }//GEN-LAST:event_b14ActionPerformed

    private void b15ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b15ActionPerformed
        // TODO add your handling code here:
        if (Memoria!=0){
        Memoria=Memoria+Double.parseDouble(Tela.getText());    
        }
        if(Memoria==0){
            Eme.setText("");
        }
    }//GEN-LAST:event_b15ActionPerformed

    private void b16ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b16ActionPerformed
        // TODO add your handling code here:
        if (Memoria!=0){
        Memoria=Memoria-Double.parseDouble(Tela.getText());
        }
        if(Memoria==0){
            Eme.setText("");
        }
    }//GEN-LAST:event_b16ActionPerformed

    private void b18ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b18ActionPerformed
        // TODO add your handling code here:
        Raiz=Double.parseDouble(Tela.getText());
        if(Raiz<0){
        Telab.setText(Telab.getText() + " sqrt("+Raiz+") ");
        Tela.setText("Entrada inválida");
        apagador=true;}
        else{
            if((int)Raiz==Raiz){
        Telab.setText(Telab.getText() + " sqrt("+String.valueOf((int)Raiz)+") ");
        teste=' ';
            }
        
    else{
        Telab.setText(Telab.getText() + " sqrt("+String.valueOf(Raiz)+") ");
        teste=' ';}
        
        Raiz=Math.sqrt(Raiz);
        Tela.setText(String.valueOf(Raiz));
        remove();
        apagador=true;}
    }//GEN-LAST:event_b18ActionPerformed

    private void b2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b2ActionPerformed
        if (Tela.getText().substring(Tela.getText().length()-1).equals(".")){
            ponto = false;
        }
       
        if (Tela.getText().length()==1){
            Tela.setText("0");
        }else
            Tela.setText(Tela.getText().substring(0, Tela.getText().length()-1));
    }//GEN-LAST:event_b2ActionPerformed

    private void b30ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b30ActionPerformed
        // TODO add your handling code here:
        if(operador==('+')){
        num2=Double.parseDouble(Tela.getText());
        num1=num1+num2;
        Tela.setText(String.valueOf(num1));
        remove();
        num1=num2=' ';
        Telab.setText("");
        apagador=true;}
        else if (operador==('-')){
        num2=Double.parseDouble(Tela.getText());
        num1=num1-num2;
        Tela.setText(String.valueOf(num1));
        remove();
        num1=num2=' ';
        apagador=true;
        Telab.setText("");}
        else if (operador==('*')){
        num2=Double.parseDouble(Tela.getText());
        num1=num1*num2;
        Tela.setText(String.valueOf(num1));
        remove();
        num1=num2=' ';
        Telab.setText("");
        apagador=true;}
        else if (operador==('/')){
        num2=Double.parseDouble(Tela.getText());
        if (num2==0){
        Tela.setText("Impossivel dividir por zero");
        apagador=true;
        }
        else{
        num1=num1/num2;
        Tela.setText(String.valueOf(num1));
        remove();
        num1=num2=' ';
        Telab.setText("");
        apagador=true;}}
        
    }//GEN-LAST:event_b30ActionPerformed

    private void b17ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b17ActionPerformed
        ponto=false;
         apagador=true;
      if (num1==' '){
      num1=Double.parseDouble(Tela.getText());
      operador=('-');
      Telab.setText(Telab.getText() + " " + Tela.getText() + " -");
      refaz=true;}
      else {
          if(!refaz){
      if(operador==('+')){
        num2=Double.parseDouble(Tela.getText());
        Telab.setText(Telab.getText() + " " + Tela.getText() + " -");
        num1=num1+num2;
        Tela.setText(String.valueOf(num1));
        remove();
        }
        else if (operador==('-')){
        num2=Double.parseDouble(Tela.getText());
        Telab.setText(Telab.getText() + " " + Tela.getText() + " -");
        num1=num1-num2;
        Tela.setText(String.valueOf(num1));
        remove();
        }
        else if (operador==('*')){
        num2=Double.parseDouble(Tela.getText());
        Telab.setText(Telab.getText() + " " + Tela.getText() + " -");
        num1=num1*num2;
        Tela.setText(String.valueOf(num1));
        remove();
        }
        else if (operador==('/')){
        num2=Double.parseDouble(Tela.getText());
        Telab.setText(Telab.getText() + " " + Tela.getText() + " -");
        num1=num1/num2;
        Tela.setText(String.valueOf(num1));
        remove();
        }operador=('-');
        refaz=true;}}
    }//GEN-LAST:event_b17ActionPerformed

    private void b22ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b22ActionPerformed
      ponto=false;
         apagador=true;
      if (num1==' '){
      num1=Double.parseDouble(Tela.getText());
      operador=('*');
      Telab.setText(Telab.getText() + " " + Tela.getText() + " *");
      refaz=true;}
      else {
          if(!refaz){
      if(operador==('+')){
        num2=Double.parseDouble(Tela.getText());
        Telab.setText(Telab.getText() + " " + Tela.getText() + " *");
        num1=num1+num2;
        Tela.setText(String.valueOf(num1));
        remove();
        }
        else if (operador==('-')){
        num2=Double.parseDouble(Tela.getText());
        Telab.setText(Telab.getText() + " " + Tela.getText() + " *");
        num1=num1-num2;
        Tela.setText(String.valueOf(num1));
        remove();
        }
        else if (operador==('*')){
        num2=Double.parseDouble(Tela.getText());
        Telab.setText(Telab.getText() + " " + Tela.getText() + " *");
        num1=num1*num2;
        Tela.setText(String.valueOf(num1));
        remove();
        }
        else if (operador==('/')){
        num2=Double.parseDouble(Tela.getText());
        Telab.setText(Telab.getText() + " " + Tela.getText() + " *");
        num1=num1/num2;
        Tela.setText(String.valueOf(num1));
        remove();
        }operador=('*');
        refaz=true;}}
    }//GEN-LAST:event_b22ActionPerformed

    private void b10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b10ActionPerformed
      ponto=false;
         apagador=true;
      if (num1==' '){
      num1=Double.parseDouble(Tela.getText());
      operador=('/');
      Telab.setText(Telab.getText() + " " + Tela.getText() + " /");
      refaz=true;}
      else {
          if(!refaz){
      if(operador==('+')){
        num2=Double.parseDouble(Tela.getText());
        if (num2==0){
            Tela.setText("Impossivel dividir por zero");
        apagador=true;
        }else{
        Telab.setText(Telab.getText() + " " + Tela.getText() + " /");
        num1=num1+num2;
        Tela.setText(String.valueOf(num1));
        remove();
        }}
        else if (operador==('-')){
        num2=Double.parseDouble(Tela.getText());
        if (num2==0){
            Tela.setText("Impossivel dividir por zero");
        apagador=true;
        }else{
        Telab.setText(Telab.getText() + " " + Tela.getText() + " /");
        num1=num1-num2;
        Tela.setText(String.valueOf(num1));
        remove();
        }}
        else if (operador==('*')){
        num2=Double.parseDouble(Tela.getText());
        if (num2==0){
            Tela.setText("Impossivel dividir por zero");
        apagador=true;
        }else{
        Telab.setText(Telab.getText() + " " + Tela.getText() + " /");
        num1=num1*num2;
        Tela.setText(String.valueOf(num1));
        remove();
        }}
        else if (operador==('/')){
        num2=Double.parseDouble(Tela.getText());
        if (num2==0){
            Tela.setText("Impossivel dividir por zero");
        apagador=true;
        }else{
            
        Telab.setText(Telab.getText() + " " + Tela.getText() + " /");
        num1=num1/num2;
        Tela.setText(String.valueOf(num1));
        remove();
        }}operador=('/');
       refaz=true;}}
    }//GEN-LAST:event_b10ActionPerformed

    private void b20ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b20ActionPerformed
        // TODO add your handling code here:
        porcent=Double.parseDouble(Tela.getText());
        num1=num1*(porcent/100);
        Tela.setText(String.valueOf(num1));
        remove();
        apagador=true;
        Telab.setText(Telab.getText() + " " + Tela.getText() + " " + operador);
        
    }//GEN-LAST:event_b20ActionPerformed

    private void TelabActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TelabActionPerformed

    }//GEN-LAST:event_TelabActionPerformed

    private void jRadioButtonMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButtonMenuItem1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jRadioButtonMenuItem1ActionPerformed

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jMenuItem1ActionPerformed

    private void jMenuItem14ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem14ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jMenuItem14ActionPerformed

    private void jMenuItem12ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem12ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jMenuItem12ActionPerformed

    private void jMenuItem19ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem19ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jMenuItem19ActionPerformed

    private void jMenuItem17ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem17ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jMenuItem17ActionPerformed

    private void EmeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EmeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_EmeActionPerformed

    private void jMenuItem22ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem22ActionPerformed
        // TODO add your handling code here:
        Sbr sbr = new Sbr();
        sbr.setVisible(true);
    }//GEN-LAST:event_jMenuItem22ActionPerformed

    private void jMenuItem16ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem16ActionPerformed
        // TODO add your handling code here:
        Ajooda ajulda = new Ajooda();
        ajulda.setVisible(true);
    }//GEN-LAST:event_jMenuItem16ActionPerformed

    private void b4KeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_b4KeyReleased
        // TODO add your handling code here:
        if(evt.getKeyCode()==KeyEvent.VK_1){
         apaga();
         zerador ("1");
         refaz=false;}
         if(evt.getKeyCode()==KeyEvent.VK_1){
         apaga();
         zerador ("1");
         refaz=false;}
        if(evt.getKeyCode()==KeyEvent.VK_2){
         apaga();
         zerador ("2");
         refaz=false;}
        if(evt.getKeyCode()==KeyEvent.VK_3){
         apaga();
         zerador ("3");
         refaz=false;}
        if(evt.getKeyCode()==KeyEvent.VK_4){
         apaga();
         zerador ("4");
         refaz=false;}
        if(evt.getKeyCode()==KeyEvent.VK_5){
         apaga();
         zerador ("5");
         refaz=false;}
        if(evt.getKeyCode()==KeyEvent.VK_6){
         apaga();
         zerador ("6");
         refaz=false;}
        if(evt.getKeyCode()==KeyEvent.VK_7){
         apaga();
         zerador ("7");
         refaz=false;}
        if(evt.getKeyCode()==KeyEvent.VK_8){
         apaga();
         zerador ("8");
         refaz=false;}
        if(evt.getKeyCode()==KeyEvent.VK_9){
         apaga();
         zerador ("9");
         refaz=false;}
        if(evt.getKeyCode()==KeyEvent.VK_0){
         apaga();
         zerador ("0");
         refaz=false;}
         
        
        
    }//GEN-LAST:event_b4KeyReleased

    private void b26KeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_b26KeyReleased
        // TODO add your handling code here:
        if(evt.getKeyCode()==KeyEvent.VK_1){
         apaga();
         zerador ("1");
         refaz=false;}
         if(evt.getKeyCode()==KeyEvent.VK_1){
         apaga();
         zerador ("1");
         refaz=false;}
        if(evt.getKeyCode()==KeyEvent.VK_2){
         apaga();
         zerador ("2");
         refaz=false;}
        if(evt.getKeyCode()==KeyEvent.VK_3){
         apaga();
         zerador ("3");
         refaz=false;}
        if(evt.getKeyCode()==KeyEvent.VK_4){
         apaga();
         zerador ("4");
         refaz=false;}
        if(evt.getKeyCode()==KeyEvent.VK_5){
         apaga();
         zerador ("5");
         refaz=false;}
        if(evt.getKeyCode()==KeyEvent.VK_6){
         apaga();
         zerador ("6");
         refaz=false;}
        if(evt.getKeyCode()==KeyEvent.VK_7){
         apaga();
         zerador ("7");
         refaz=false;}
        if(evt.getKeyCode()==KeyEvent.VK_8){
         apaga();
         zerador ("8");
         refaz=false;}
        if(evt.getKeyCode()==KeyEvent.VK_9){
         apaga();
         zerador ("9");
         refaz=false;}
        if(evt.getKeyCode()==KeyEvent.VK_0){
         apaga();
         zerador ("0");
         refaz=false;}
    }//GEN-LAST:event_b26KeyReleased

    private void b19KeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_b19KeyReleased
        // TODO add your handling code here:
        if(evt.getKeyCode()==KeyEvent.VK_1){
         apaga();
         zerador ("1");
         refaz=false;}
         if(evt.getKeyCode()==KeyEvent.VK_1){
         apaga();
         zerador ("1");
         refaz=false;}
        if(evt.getKeyCode()==KeyEvent.VK_2){
         apaga();
         zerador ("2");
         refaz=false;}
        if(evt.getKeyCode()==KeyEvent.VK_3){
         apaga();
         zerador ("3");
         refaz=false;}
        if(evt.getKeyCode()==KeyEvent.VK_4){
         apaga();
         zerador ("4");
         refaz=false;}
        if(evt.getKeyCode()==KeyEvent.VK_5){
         apaga();
         zerador ("5");
         refaz=false;}
        if(evt.getKeyCode()==KeyEvent.VK_6){
         apaga();
         zerador ("6");
         refaz=false;}
        if(evt.getKeyCode()==KeyEvent.VK_7){
         apaga();
         zerador ("7");
         refaz=false;}
        if(evt.getKeyCode()==KeyEvent.VK_8){
         apaga();
         zerador ("8");
         refaz=false;}
        if(evt.getKeyCode()==KeyEvent.VK_9){
         apaga();
         zerador ("9");
         refaz=false;}
        if(evt.getKeyCode()==KeyEvent.VK_0){
         apaga();
         zerador ("0");
         refaz=false;}
    }//GEN-LAST:event_b19KeyReleased

    private void b5KeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_b5KeyReleased
        // TODO add your handling code here:
        if(evt.getKeyCode()==KeyEvent.VK_1){
         apaga();
         zerador ("1");
         refaz=false;}
         if(evt.getKeyCode()==KeyEvent.VK_1){
         apaga();
         zerador ("1");
         refaz=false;}
        if(evt.getKeyCode()==KeyEvent.VK_2){
         apaga();
         zerador ("2");
         refaz=false;}
        if(evt.getKeyCode()==KeyEvent.VK_3){
         apaga();
         zerador ("3");
         refaz=false;}
        if(evt.getKeyCode()==KeyEvent.VK_4){
         apaga();
         zerador ("4");
         refaz=false;}
        if(evt.getKeyCode()==KeyEvent.VK_5){
         apaga();
         zerador ("5");
         refaz=false;}
        if(evt.getKeyCode()==KeyEvent.VK_6){
         apaga();
         zerador ("6");
         refaz=false;}
        if(evt.getKeyCode()==KeyEvent.VK_7){
         apaga();
         zerador ("7");
         refaz=false;}
        if(evt.getKeyCode()==KeyEvent.VK_8){
         apaga();
         zerador ("8");
         refaz=false;}
        if(evt.getKeyCode()==KeyEvent.VK_9){
         apaga();
         zerador ("9");
         refaz=false;}
        if(evt.getKeyCode()==KeyEvent.VK_0){
         apaga();
         zerador ("0");
         refaz=false;}
    }//GEN-LAST:event_b5KeyReleased

    private void b27KeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_b27KeyReleased
        // TODO add your handling code here:
        if(evt.getKeyCode()==KeyEvent.VK_1){
         apaga();
         zerador ("1");
         refaz=false;}
         if(evt.getKeyCode()==KeyEvent.VK_1){
         apaga();
         zerador ("1");
         refaz=false;}
        if(evt.getKeyCode()==KeyEvent.VK_2){
         apaga();
         zerador ("2");
         refaz=false;}
        if(evt.getKeyCode()==KeyEvent.VK_3){
         apaga();
         zerador ("3");
         refaz=false;}
        if(evt.getKeyCode()==KeyEvent.VK_4){
         apaga();
         zerador ("4");
         refaz=false;}
        if(evt.getKeyCode()==KeyEvent.VK_5){
         apaga();
         zerador ("5");
         refaz=false;}
        if(evt.getKeyCode()==KeyEvent.VK_6){
         apaga();
         zerador ("6");
         refaz=false;}
        if(evt.getKeyCode()==KeyEvent.VK_7){
         apaga();
         zerador ("7");
         refaz=false;}
        if(evt.getKeyCode()==KeyEvent.VK_8){
         apaga();
         zerador ("8");
         refaz=false;}
        if(evt.getKeyCode()==KeyEvent.VK_9){
         apaga();
         zerador ("9");
         refaz=false;}
        if(evt.getKeyCode()==KeyEvent.VK_0){
         apaga();
         zerador ("0");
         refaz=false;}
    }//GEN-LAST:event_b27KeyReleased

    private void b25KeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_b25KeyReleased
        // TODO add your handling code here:
        if(evt.getKeyCode()==KeyEvent.VK_1){
         apaga();
         zerador ("1");
         refaz=false;}
         if(evt.getKeyCode()==KeyEvent.VK_1){
         apaga();
         zerador ("1");
         refaz=false;}
        if(evt.getKeyCode()==KeyEvent.VK_2){
         apaga();
         zerador ("2");
         refaz=false;}
        if(evt.getKeyCode()==KeyEvent.VK_3){
         apaga();
         zerador ("3");
         refaz=false;}
        if(evt.getKeyCode()==KeyEvent.VK_4){
         apaga();
         zerador ("4");
         refaz=false;}
        if(evt.getKeyCode()==KeyEvent.VK_5){
         apaga();
         zerador ("5");
         refaz=false;}
        if(evt.getKeyCode()==KeyEvent.VK_6){
         apaga();
         zerador ("6");
         refaz=false;}
        if(evt.getKeyCode()==KeyEvent.VK_7){
         apaga();
         zerador ("7");
         refaz=false;}
        if(evt.getKeyCode()==KeyEvent.VK_8){
         apaga();
         zerador ("8");
         refaz=false;}
        if(evt.getKeyCode()==KeyEvent.VK_9){
         apaga();
         zerador ("9");
         refaz=false;}
        if(evt.getKeyCode()==KeyEvent.VK_0){
         apaga();
         zerador ("0");
         refaz=false;}
    }//GEN-LAST:event_b25KeyReleased

    private void b28KeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_b28KeyReleased
        // TODO add your handling code here:
        if(evt.getKeyCode()==KeyEvent.VK_1){
         apaga();
         zerador ("1");
         refaz=false;}
         if(evt.getKeyCode()==KeyEvent.VK_1){
         apaga();
         zerador ("1");
         refaz=false;}
        if(evt.getKeyCode()==KeyEvent.VK_2){
         apaga();
         zerador ("2");
         refaz=false;}
        if(evt.getKeyCode()==KeyEvent.VK_3){
         apaga();
         zerador ("3");
         refaz=false;}
        if(evt.getKeyCode()==KeyEvent.VK_4){
         apaga();
         zerador ("4");
         refaz=false;}
        if(evt.getKeyCode()==KeyEvent.VK_5){
         apaga();
         zerador ("5");
         refaz=false;}
        if(evt.getKeyCode()==KeyEvent.VK_6){
         apaga();
         zerador ("6");
         refaz=false;}
        if(evt.getKeyCode()==KeyEvent.VK_7){
         apaga();
         zerador ("7");
         refaz=false;}
        if(evt.getKeyCode()==KeyEvent.VK_8){
         apaga();
         zerador ("8");
         refaz=false;}
        if(evt.getKeyCode()==KeyEvent.VK_9){
         apaga();
         zerador ("9");
         refaz=false;}
        if(evt.getKeyCode()==KeyEvent.VK_0){
         apaga();
         zerador ("0");
         refaz=false;}
    }//GEN-LAST:event_b28KeyReleased

    private void b29KeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_b29KeyReleased
        // TODO add your handling code here:
        if(evt.getKeyCode()==KeyEvent.VK_1){
         apaga();
         zerador ("1");
         refaz=false;}
         if(evt.getKeyCode()==KeyEvent.VK_1){
         apaga();
         zerador ("1");
         refaz=false;}
        if(evt.getKeyCode()==KeyEvent.VK_2){
         apaga();
         zerador ("2");
         refaz=false;}
        if(evt.getKeyCode()==KeyEvent.VK_3){
         apaga();
         zerador ("3");
         refaz=false;}
        if(evt.getKeyCode()==KeyEvent.VK_4){
         apaga();
         zerador ("4");
         refaz=false;}
        if(evt.getKeyCode()==KeyEvent.VK_5){
         apaga();
         zerador ("5");
         refaz=false;}
        if(evt.getKeyCode()==KeyEvent.VK_6){
         apaga();
         zerador ("6");
         refaz=false;}
        if(evt.getKeyCode()==KeyEvent.VK_7){
         apaga();
         zerador ("7");
         refaz=false;}
        if(evt.getKeyCode()==KeyEvent.VK_8){
         apaga();
         zerador ("8");
         refaz=false;}
        if(evt.getKeyCode()==KeyEvent.VK_9){
         apaga();
         zerador ("9");
         refaz=false;}
        if(evt.getKeyCode()==KeyEvent.VK_0){
         apaga();
         zerador ("0");
         refaz=false;}
    }//GEN-LAST:event_b29KeyReleased

    private void b12KeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_b12KeyReleased
        // TODO add your handling code here:
        if(evt.getKeyCode()==KeyEvent.VK_1){
         apaga();
         zerador ("1");
         refaz=false;}
         if(evt.getKeyCode()==KeyEvent.VK_1){
         apaga();
         zerador ("1");
         refaz=false;}
        if(evt.getKeyCode()==KeyEvent.VK_2){
         apaga();
         zerador ("2");
         refaz=false;}
        if(evt.getKeyCode()==KeyEvent.VK_3){
         apaga();
         zerador ("3");
         refaz=false;}
        if(evt.getKeyCode()==KeyEvent.VK_4){
         apaga();
         zerador ("4");
         refaz=false;}
        if(evt.getKeyCode()==KeyEvent.VK_5){
         apaga();
         zerador ("5");
         refaz=false;}
        if(evt.getKeyCode()==KeyEvent.VK_6){
         apaga();
         zerador ("6");
         refaz=false;}
        if(evt.getKeyCode()==KeyEvent.VK_7){
         apaga();
         zerador ("7");
         refaz=false;}
        if(evt.getKeyCode()==KeyEvent.VK_8){
         apaga();
         zerador ("8");
         refaz=false;}
        if(evt.getKeyCode()==KeyEvent.VK_9){
         apaga();
         zerador ("9");
         refaz=false;}
        if(evt.getKeyCode()==KeyEvent.VK_0){
         apaga();
         zerador ("0");
         refaz=false;}
    }//GEN-LAST:event_b12KeyReleased

    private void b1KeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_b1KeyReleased
        // TODO add your handling code here:
        if(evt.getKeyCode()==KeyEvent.VK_1){
         apaga();
         zerador ("1");
         refaz=false;}
         if(evt.getKeyCode()==KeyEvent.VK_1){
         apaga();
         zerador ("1");
         refaz=false;}
        if(evt.getKeyCode()==KeyEvent.VK_2){
         apaga();
         zerador ("2");
         refaz=false;}
        if(evt.getKeyCode()==KeyEvent.VK_3){
         apaga();
         zerador ("3");
         refaz=false;}
        if(evt.getKeyCode()==KeyEvent.VK_4){
         apaga();
         zerador ("4");
         refaz=false;}
        if(evt.getKeyCode()==KeyEvent.VK_5){
         apaga();
         zerador ("5");
         refaz=false;}
        if(evt.getKeyCode()==KeyEvent.VK_6){
         apaga();
         zerador ("6");
         refaz=false;}
        if(evt.getKeyCode()==KeyEvent.VK_7){
         apaga();
         zerador ("7");
         refaz=false;}
        if(evt.getKeyCode()==KeyEvent.VK_8){
         apaga();
         zerador ("8");
         refaz=false;}
        if(evt.getKeyCode()==KeyEvent.VK_9){
         apaga();
         zerador ("9");
         refaz=false;}
        if(evt.getKeyCode()==KeyEvent.VK_0){
         apaga();
         zerador ("0");
         refaz=false;}
    }//GEN-LAST:event_b1KeyReleased

    private void b8KeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_b8KeyReleased
        // TODO add your handling code here:
        if(evt.getKeyCode()==KeyEvent.VK_1){
         apaga();
         zerador ("1");
         refaz=false;}
         if(evt.getKeyCode()==KeyEvent.VK_1){
         apaga();
         zerador ("1");
         refaz=false;}
        if(evt.getKeyCode()==KeyEvent.VK_2){
         apaga();
         zerador ("2");
         refaz=false;}
        if(evt.getKeyCode()==KeyEvent.VK_3){
         apaga();
         zerador ("3");
         refaz=false;}
        if(evt.getKeyCode()==KeyEvent.VK_4){
         apaga();
         zerador ("4");
         refaz=false;}
        if(evt.getKeyCode()==KeyEvent.VK_5){
         apaga();
         zerador ("5");
         refaz=false;}
        if(evt.getKeyCode()==KeyEvent.VK_6){
         apaga();
         zerador ("6");
         refaz=false;}
        if(evt.getKeyCode()==KeyEvent.VK_7){
         apaga();
         zerador ("7");
         refaz=false;}
        if(evt.getKeyCode()==KeyEvent.VK_8){
         apaga();
         zerador ("8");
         refaz=false;}
        if(evt.getKeyCode()==KeyEvent.VK_9){
         apaga();
         zerador ("9");
         refaz=false;}
        if(evt.getKeyCode()==KeyEvent.VK_0){
         apaga();
         zerador ("0");
         refaz=false;}
    }//GEN-LAST:event_b8KeyReleased

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Calc.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Calc.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Calc.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Calc.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Calc().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Clearev;
    private javax.swing.JTextField Eme;
    private javax.swing.JButton Ponto;
    private javax.swing.JTextField Tela;
    private javax.swing.JTextField Telab;
    private javax.swing.JButton b1;
    private javax.swing.JButton b10;
    private javax.swing.JButton b11;
    private javax.swing.JButton b12;
    private javax.swing.JButton b13;
    private javax.swing.JButton b14;
    private javax.swing.JButton b15;
    private javax.swing.JButton b16;
    private javax.swing.JButton b17;
    private javax.swing.JButton b18;
    private javax.swing.JButton b19;
    private javax.swing.JButton b2;
    private javax.swing.JButton b20;
    private javax.swing.JButton b21;
    private javax.swing.JButton b22;
    private javax.swing.JButton b24;
    private javax.swing.JButton b25;
    private javax.swing.JButton b26;
    private javax.swing.JButton b27;
    private javax.swing.JButton b28;
    private javax.swing.JButton b29;
    private javax.swing.JButton b3;
    private javax.swing.JButton b30;
    private javax.swing.JButton b4;
    private javax.swing.JButton b5;
    private javax.swing.JButton b8;
    private javax.swing.JButton b9;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenu jMenu4;
    private javax.swing.JMenu jMenu5;
    private javax.swing.JMenu jMenu6;
    private javax.swing.JMenu jMenu7;
    private javax.swing.JMenu jMenu8;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuBar jMenuBar2;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem10;
    private javax.swing.JMenuItem jMenuItem11;
    private javax.swing.JMenuItem jMenuItem12;
    private javax.swing.JMenuItem jMenuItem13;
    private javax.swing.JMenuItem jMenuItem14;
    private javax.swing.JMenuItem jMenuItem15;
    private javax.swing.JMenuItem jMenuItem16;
    private javax.swing.JMenuItem jMenuItem17;
    private javax.swing.JMenuItem jMenuItem18;
    private javax.swing.JMenuItem jMenuItem19;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JMenuItem jMenuItem20;
    private javax.swing.JMenuItem jMenuItem21;
    private javax.swing.JMenuItem jMenuItem22;
    private javax.swing.JMenuItem jMenuItem3;
    private javax.swing.JMenuItem jMenuItem4;
    private javax.swing.JMenuItem jMenuItem5;
    private javax.swing.JMenuItem jMenuItem6;
    private javax.swing.JMenuItem jMenuItem7;
    private javax.swing.JMenuItem jMenuItem8;
    private javax.swing.JMenuItem jMenuItem9;
    private javax.swing.JRadioButtonMenuItem jRadioButtonMenuItem1;
    private javax.swing.JRadioButtonMenuItem jRadioButtonMenuItem2;
    private javax.swing.JRadioButtonMenuItem jRadioButtonMenuItem4;
    private javax.swing.JPopupMenu.Separator jSeparator1;
    private javax.swing.JPopupMenu.Separator jSeparator2;
    private javax.swing.JPopupMenu.Separator jSeparator3;
    // End of variables declaration//GEN-END:variables
}
